collabCTF/urls.py
from django.conf.urls import patterns, include, url, static
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'collabCTF.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'collabCTF.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^settings$', 'collabCTF.views.user_settings', name='settings'),
    url(r'^profile$', 'collabCTF.views.profile', name='profile'),
    url(r'^login$', 'collabCTF.views.log_in', name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': "/login"}, name='logout'),
    url(r'^register$', 'collabCTF.views.register', name='register'),
    url(r'^reports$', 'collabCTF.views.reports', name='reports'),
    url(r'^ctf-tools$', 'tools.views.ctf_tools', name='ctf_tools'),
    url(r'^ctf/add$', 'competition.views.add_ctf', name='add_ctf'),
    url(r'^ctf/(?P<ctf_slug>[a-z\d_\-]+)/$', 'competition.views.view_ctf', name='view_ctf'),
    url(r'^ctf/(?P<ctf_slug>[a-z\d_\-]+)/update$', 'competition.views.update_ctf', name='update_ctf'),
    url(r'^ctf/(?P<ctf_slug>[a-z\d_\-]+)/delete$', 'competition.views.delete_ctf', name='delete_ctf'),
    url(r'^ctf/(?P<ctf_slug>[a-z\d_\-]+)/add$', 'competition.views.add_challenge', name='add_challenge'),
    url(r'^ctf/(?P<ctf_slug>[a-z\d_\-]+)/(?P<chall_slug>[a-z\d_\-]+)/$', 'competition.views.view_challenge',
        name='view_challenge'),
    url(r'^ctf/(?P<ctf_slug>[a-z\d_\-]+)/(?P<chall_slug>[a-z\d_\-]+)/update$', 'competition.views.update_challenge',
        name='update_challenge'),
    url(r'^ctf/(?P<ctf_slug>[a-z\d_\-]+)/(?P<chall_slug>[a-z\d_\-]+)/delete$', 'competition.views.delete_challenge',
        name='delete_challenge'),
    url(r'ctf/(?P<ctf_slug>[a-z\d_\-]+)/(?P<chall_slug>[a-z\d_\-]+)/add', 'competition.views.add_file',
        name='add_file'),

    # ajax
    url(r'^ctf/(?P<ctf_slug>[a-z\d_\-]+)/.chart$', 'competition.ajax.chart_data', name='ctf_chart'),
    url(r'^tools/.hash$', 'tools.ajax.hash_val', name='tools_hash'),
    url(r'^tools/.rot$', 'tools.ajax.rot_val', name='tools_rot'),
    url(r'^tools/.base_conversions$', 'tools.ajax.base_conversion_val', name='tools_base_conversion'),
    url(r'^tools/.xor$', 'tools.ajax.xor_val', name='tools_xor'),
    url(r'^tools/.url-quote$', 'tools.ajax.quote_url', name='tools_quote'),
    url(r'^tools/.url-unquote$', 'tools.ajax.unquote_url', name='tools_unquote'),
    url(r'^.challenge-visit$', 'competition.ajax.track_challenge_visit', name='track_challenge_visit'),
)

if settings.DEBUG:
    if 'MEDIA_ROOT' in dir(settings):
        media_root = settings.MEDIA_ROOT
    else:
        media_root = 'files'
    urlpatterns += static.static(settings.MEDIA_URL, document_root=media_root)

competition/models.py
import os
from django.contrib.auth.models import User
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models


class Competition(models.Model):
    name = models.CharField('Name', max_length=255, unique=True)
    slug = models.SlugField(unique=True)
    url = models.URLField('Competition URL', blank=True)
    start_time = models.DateTimeField(blank=True, null=True)
    end_time = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        return self.name

    __str__ = __unicode__

    def get_absolute_url(self):
        return reverse('view_ctf', kwargs={'ctf_slug': self.slug})


class Challenge(models.Model):
    NOT_STARTED = 0
    IN_PROGRESS = 1
    SOLVED = 2

    PROGRESS_CHOICES = (
        (NOT_STARTED, 'Not Started'),
        (IN_PROGRESS, 'In Progress'),
        (SOLVED, 'Solved')
    )

    name = models.CharField('Name', max_length=255)
    slug = models.SlugField()
    progress = models.PositiveSmallIntegerField(choices=PROGRESS_CHOICES)
    num_progress = models.FloatField('Progress %', default=0)
    point_value = models.FloatField(default=0)

    competition = models.ForeignKey(Competition, related_name='challenges')
    last_viewed = models.DateTimeField(auto_created=True)

    viewers = models.ManyToManyField(User, related_name='challenges_viewed')
    participants = models.ManyToManyField(User, related_name='challenges_participated')

    def __unicode__(self):
        return self.name

    __str__ = __unicode__

    def get_absolute_url(self):
        return reverse('view_challenge', kwargs={'ctf_slug': self.competition.slug, 'chall_slug': self.slug})

    def last_viewed_display(self):
        if self.last_viewed == 0:
            return 'Never'
        else:
            return self.last_viewed

    class Meta:
        unique_together = ('name', 'competition')
        ordering = ('progress',)


class ChallengeFile(models.Model):
    file = models.FileField(upload_to='files/')
    ctime = models.DateTimeField(auto_created=True)
    mtime = models.DateTimeField(auto_now=True)
    challenge = models.ForeignKey(Challenge, related_name='files')

    def __unicode__(self):
        return self.file.name

    __str__ = __unicode__

    def filename(self):
        return os.path.basename(self.file.name)


class Tag(models.Model):
    tag = models.SlugField()
    is_category = models.BooleanField(default=False)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    def __unicode__(self):
        return self.tag

    __str__ = __unicode__

competition/views.py
from datetime import datetime
import hashlib

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.template import RequestContext
from django.utils.text import slugify
from django.views.decorators.http import require_safe, require_http_methods, require_POST

from competition.forms import CompetitionModelForm, ChallengeModelForm, ChallengeFileModelForm
from competition.models import Competition, Challenge


@login_required
@require_http_methods(['GET', 'POST'])
def add_ctf(request):
    if request.method == 'GET':
        form = CompetitionModelForm()
        data = {
            'form': form
        }
        return render_to_response('ctf/add.html', data, RequestContext(request))

    elif request.method == 'POST':
        form = CompetitionModelForm(request.POST)
        data = {
            'form': form
        }

        if form.is_valid():
            competition = form.save(commit=False)
            competition.slug = slugify(competition.name)
            competition.save()
            data['competition'] = competition
            return redirect(competition.get_absolute_url())

        # url tbd
        return render_to_response('ctf/add.html', data, RequestContext(request))


@login_required
@require_http_methods(['GET', 'POST'])
def update_ctf(request, ctf_slug):
    ctf = get_object_or_404(Competition.objects, slug=ctf_slug)
    if request.method == 'GET':
        data = {
            'ctf': ctf,
            'form': CompetitionModelForm(instance=ctf)
        }
        return render_to_response('ctf/update.html', data, RequestContext(request))

    elif request.method == 'POST':
        form = CompetitionModelForm(request.POST, instance=ctf)
        saved = False
        if form.is_valid():
            form.save()
            saved = True

        data = {
            'ctf': ctf,
            'form': form,
            'saved': saved
        }
        return render_to_response('ctf/update.html', data, RequestContext(request))


@login_required
@require_safe
def view_ctf(request, ctf_slug):
    ctf = get_object_or_404(Competition.objects.prefetch_related('challenges'), slug=ctf_slug)
    challenges = ctf.challenges.all()
    data = {
        'ctf': ctf,
        'challenges': challenges
    }

    return render_to_response('ctf/overview.html', data, RequestContext(request))


@login_required
@require_POST
def delete_ctf(request, ctf_slug):
    ctf = get_object_or_404(Competition.objects, slug=ctf_slug)
    data = {
        'ctf': ctf
    }
    response = render_to_response('ctf/removed.html', data)
    ctf.delete()
    return response


@login_required
@require_http_methods(['GET', 'POST'])
def add_challenge(request, ctf_slug):
    ctf = get_object_or_404(Competition.objects, slug=ctf_slug)
    if request.method == 'GET':
        form = ChallengeModelForm(initial={'competition': ctf})
        data = {
            'form': form,
            'ctf': ctf
        }
        return render_to_response('ctf/challenge/add.html', data, RequestContext(request))

    elif request.method == 'POST':
        form = ChallengeModelForm(request.POST)
        data = {
            'form': form,
            'ctf': ctf
        }

        if form.is_valid():
            challenge = form.save(commit=False)
            challenge.competition = ctf
            challenge.last_viewed = datetime.now()
            challenge.slug = slugify(challenge.name)
            challenge.save()
            return redirect(ctf.get_absolute_url())

        return render_to_response('ctf/challenge/add.html', data, RequestContext(request))


@login_required
@require_safe
def view_challenge(request, ctf_slug, chall_slug):
    ctf = get_object_or_404(Competition.objects, slug=ctf_slug)
    challenge = get_object_or_404(Challenge.objects.prefetch_related('files'), competition=ctf, slug=chall_slug)

    data = {
        'ctf': ctf,
        'challenge': challenge,
        'files': challenge.files.all(),
        'hash': hashlib.sha1(challenge.name.encode('utf8') + settings.SECRET_KEY.encode('utf8')).hexdigest()
    }

    return render_to_response('ctf/challenge/overview.html', data, RequestContext(request))


@login_required
@require_http_methods(['GET', 'POST'])
def update_challenge(request, ctf_slug, chall_slug):
    ctf = get_object_or_404(Competition.objects, slug=ctf_slug)
    challenge = get_object_or_404(Challenge.objects, competition=ctf, slug=chall_slug)

    if request.method == 'GET':
        data = {
            'ctf': ctf,
            'challenge': challenge,
            'form': ChallengeModelForm(instance=challenge)
        }
        return render_to_response('ctf/challenge/update.html', data, RequestContext(request))

    elif request.method == 'POST':
        form = ChallengeModelForm(request.POST, instance=challenge)
        if form.is_valid():
            # add timestamp and participant
            challenge = form.save(commit=False)
            challenge.last_viewed = datetime.now()
            challenge.viewers.add(request.user)
            challenge.participants.add(request.user)
            challenge.save()

            return redirect(challenge.get_absolute_url())

        data = {
            'ctf': ctf,
            'challenge': challenge,
            'form': ChallengeModelForm(instance=challenge),
        }
        return render_to_response('ctf/challenge/update.html', data, RequestContext(request))


@login_required
@require_http_methods(['GET', 'POST'])
def delete_challenge(request, ctf_slug, chall_slug):
    ctf = get_object_or_404(Competition.objects, slug=ctf_slug)
    challenge = get_object_or_404(Challenge.objects, competition=ctf, slug=chall_slug)
    data = {
        'ctf': ctf,
        'challenge': challenge
    }
    response = render_to_response('ctf/challenge/deleted.html', data, RequestContext(request))
    challenge.delete()
    return response


@login_required
@require_http_methods(['GET', 'POST'])
def add_file(request, ctf_slug, chall_slug):
    ctf = get_object_or_404(Competition.objects, slug=ctf_slug)
    challenge = get_object_or_404(Challenge.objects, competition=ctf, slug=chall_slug)

    data = {
        'ctf': ctf,
        'challenge': challenge,
    }

    if request.method == 'GET':
        data['form'] = ChallengeFileModelForm()
        return render_to_response('ctf/challenge/files/add.html', data, RequestContext(request))
    elif request.method == 'POST':
        form = ChallengeFileModelForm(request.POST, request.FILES)
        if form.is_valid():
            upfile = form.save(commit=False)
            upfile.challenge = challenge
            upfile.ctime = datetime.now()
            upfile.mtime = datetime.now()
            upfile.save()
            return redirect('view_challenge', ctf_slug=ctf_slug, chall_slug=chall_slug)
        else:
            data['form'] = ChallengeFileModelForm()
            return render_to_response('ctf/challenge/files/add.html', data, RequestContext(request))

competition/templates/ctf/challenge/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block subtitle %}- Add Challenge{% endblock %}
{% block content %}
    <div class="small-9 medium-10 columns">
        <h1 class="page-header">{{ ctf.name }} <small>Add Challenge</small></h1>

        <div class="row">
            <div class="small-12 medium-8 large-6 columns">
                {% crispy form form.add_helper %}
            </div>
        </div>
    </div>
{% endblock %}

competition/templates/ctf/challenge/deleted.html
{% extends 'base.html' %}
{% block subtitle %}- {{ challenge.name }}{% endblock %}
{% block content %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Challenge Deleted</h1>

        <div class="row">
            <div class="col-sm-12">
                <p>{{ challenge.name }} has been deleted. You wil be redirected to the CTF overview in 5 seconds.</p>
                <script>setTimeout(function() {document.location = '{% url 'view_ctf' ctf.slug %}';}, 5000) </script>
            </div>
        </div>
    </div>
{% endblock %}

competition/templates/ctf/challenge/overview.html
{% extends 'base.html' %}
{% load static %}

{% block subtitle %}- {{ challenge.name }}{% endblock %}
{% block ctfchallenge_class %}active{% endblock %}
{% block content %}

    <div class="small-9 medium-10 columns">
        {% with challenge.get_progress_display as status %}
            <h1 id="challenge-header" class="{{ status|slugify }}">{{ challenge.name }}
                <small class="status">{{ status }}</small>
                <span class="right">
                    <a class="edit" href="{% url 'update_challenge' ctf.slug challenge.slug %}">&#9998;</a>
                    <a class="delete" href="#" data-reveal-id="delete-challenge">&#215;</a>
                </span>
            </h1>
        {% endwith %}
        {% include 'breadcrumbs.html' with state='overview' %}

        <h2>Files</h2>
        {% if files %}
            <table id="uploaded-files" class="table table-striped">
                <thead>
                <tr>
                    <th>Filename</th>
                    <th>Upload Time</th>
                    <th>Uploaded By</th>
                    <th>Link</th>
                </tr>
                </thead>
                <tbody>
                {% for upfile in files %}
                <tr>
                    <td>{{ upfile.filename }}</td>
                    <td>{{ upfile.ctime }}</td>
                    <td>Sample User</td>
                    <td><a href="{{ upfile.file.url }}">Download</a></td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="5"><a href="{% url 'add_file' ctf.slug challenge.slug %}">Upload New File</a></td>
                </tr>
                </tbody>
            </table>
        {% else %}
            <p>No files uploaded. <a href="{% url 'add_file' ctf.slug challenge.slug %}">Click here to add a file.</a></p>
        {% endif %}
        <h2 class="sub-header">Collaborative Document</h2>
            <p>Your online collaborative document for this challenge is <a href="https://etherpad.wikimedia.org/p/{{hash}}">available here.</a>
            </p>
    </div>
    <div id="delete-challenge" class="delete-modal reveal-modal small" data-reveal>
        <h3>Challenge Deletion Confirmation</h3>
        <p>Are you sure that you want to delete {{ ctf.name }}?</p>
        <form class="text-right" action="delete" method="post">
            {% csrf_token %}
            <input class="button secondary" type="reset" value="Cancel"/>
            <input class="button alert" type="submit" value="Delete"/>
            <a class="close-reveal-modal">&#215;</a>
        </form>
    </div>
{% endblock %}

{% block extra_scripts %}
    <script>$.post('/.challenge-visit', {url: location.pathname});</script>
{% endblock %}

competition/templates/ctf/challenge/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block subtitle %}- {{ challenge.name }}{% endblock %}
{% block content %}
    <div class="small-9 medium-10 columns">
        <h1>{{ challenge.name }} <small>Update</small></h1>
        {% include 'breadcrumbs.html' with state='update' %}

        <div class="row">
            <div class="small-12 medium-8 large-6 columns">
                {% crispy form form.update_helper %}
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_scripts %}
    <script>$.post('/.challenge-visit', {url: location.pathname});</script>
{% endblock %}